#  * Copyright (C) Mohammad (Sina) Jalalvandi (parsidate) 2024-2025 <jalalvandi.sina@gmail.com>
#  * Version : 1.3.3
#  * 128558ad-c066-4c4a-9b93-bca896bf4465
#  * Cargo.toml

[package]
name = "parsidate" 
version = "1.3.3"
edition = "2024"
description = "provides comprehensive Full functionality for working with the Persian (Jalali/Shamsi) calendar system in Rust." 
license = "Apache-2.0" 
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
homepage = "https://sinajalalvandi.ir/projects/index/parsidate/"
repository = "https://github.com/jalalvandi/ParsiDate"
readme = "README.md"
documentation = "https://docs.rs/parsidate/"
license-file = "LICENSE"
keywords = ["date", "jalali","calendar","persian","persiandate"]
categories = ["date-and-time", "localization","internationalization"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]
