[package]
name = "parsidate" 
version = "0.1.2"
edition = "2021"
description = "A Rust library for converting between Gregorian and Persian (Jalali) dates" 
license = "MIT" 
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
homepage = "https://sinajalalvandi.ir"
repository = "https://github.com/jalalvandi/ParsiDate"
readme = "README.md"
keywords = ["date", "jalali","calendar","persian","persiandate"]
categories = ["date-and-time", "localization","internationalization"]

[dependencies]
chrono = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]