[package]
name = "parsidate" 
version = "0.1.0"
edition = "2021"
description = "A Rust library for converting between Gregorian and Persian (Jalali) dates" 
license = "MIT" 
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
homepage = "https://sinajalalvandi.ir"
repository = "https://github.com/jalalvandi/ParsiDate"
readme = "README.md"
keywords = ["date", "time","calendar","persian","persiandate"]
categories = ["date-and-time", "localization"]

[dependencies]
chrono = "0.4"