[package]
name = "parsidate" 
version = "1.3.2"
edition = "2021"
description = "provides comprehensive Full functionality for working with the Persian (Jalali/Shamsi) calendar system in Rust." 
license = "Apache-2.0" 
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
homepage = "https://sinajalalvandi.ir"
repository = "https://github.com/jalalvandi/ParsiDate"
readme = "README.md"
documentation = "https://docs.rs/parsidate/"
license-file = "LICENSE"
keywords = ["date", "jalali","calendar","persian","persiandate"]
categories = ["date-and-time", "localization","internationalization"]
[badges]
maintenance = { status = "actively-developed" }
[dependencies]
chrono = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]