#  * Cargo.toml
#  * Copyright (C) Mohammad (Sina) Jalalvandi (parsidate) 2024-2025 <jalalvandi.sina@gmail.com>
#  * Version : 1.4.0
#  * eb1f0cae-a178-41e5-b109-47f208e77913


[package]
name = "parsidate" 
version = "1.4.0"
edition = "2024"
description = "provides comprehensive full functionality for working with the Persian (Jalali/Shamsi) calendar system in Rust." 
license = "Apache-2.0" 
authors = ["Sina Jalalvandi <Jalalvandi.Sina@gmail.com>"] 
homepage = "https://crates.io/crates/parsidate"
repository = "https://github.com/jalalvandi/ParsiDate"
readme = "README.md"
documentation = "https://docs.rs/parsidate/"
keywords = ["date", "jalali","calendar","persian","shamsi"]
categories = ["date-and-time", "localization","internationalization"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "^0.4"
serde = { version = "^1.0", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]
